import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const ragilac = localFont({
  src: [
    {
      path: "/../public/fonts/Ragilac.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-ragilac", // CSS variable for ragilac
});

const redHat = localFont({
  src: [
    {
      path: "/../public/fonts/RedHatDisplay-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "/../public/fonts/RedHatDisplay-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "/../public/fonts/RedHatDisplay-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "/../public/fonts/RedHatDisplay-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-redHat", // CSS variable for redHat
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ragilac.variable} ${redHat.variable} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
